jaffle_shop:

  target: dev
  outputs:
    dev:
      type: snowflake
      account:  wvb58768
      
      user: "{{env_var('SNOWFLAKE_USERNAME')}}"
      password:  "{{env_var('SNOWFLAKE_PASSWORD')}}"

      role:  ACCOUNTADMIN
      database:  JAFFLE_SHOP
      warehouse:  JAFFLE_WH
      schema:  DBT_DEV
      threads:  1
      client_session_keep_alive:  True